version: '3.8'

services:
  spring-boot-app:
    build:
      context: ./api
    ports:
      - "8080:8080"
    networks:
      - app-network

  next-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
