version: '3'
services:
  spring-boot-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  next-js-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - spring-boot-app