spring:
  application:
    name: starling

starling:
  baseUrl: https://api-sandbox.starlingbank.com
  accessToken: eyJhbGciOiJQUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_21Ty5KjMAz8lSnOoyle4XWb2_7AfoCQ5cQ1YFO2yezU1v77mhhCSOVGd-vRssTfRDmXdAlOCgSP5sN5tIPS5x711weZMXlP3NyHCM7xxFyWUBR1A6UsEPqaazhlZdmeOK3SqgjB_GdKuqzOyixrmjx_TxT6SKRFXi4EEplZ-19mEGx_K7HWLqq0gbxtayjrvAGk0EVwm7ai6XM6paG2N1-s14wK67yWDCXlCCVyA61sU6iYZZVXkqpGhoww1icRO7f3aUkS1H3ZL6k1YHFKAWUjijorWsqrZWAyEy-PEp3C5WYVNI7cWUbx9iT4n-lJUIK1V1KxPfKDcv7ArEAIG0x2LJS_g6h4j3QZ-R6542-rPL_h7C_GKhdWBkoLdVVixiEG9zigptUaoRVARntrhthoYVbNaKnsiF4ZDUaCnLVYDdDsvBm3OXhEtWaPqAV67gQPHHxs8BY2sseAsKMAF3HDt8wJf5g3KYK1SAR7EKgRz2vNqO2f4C1qh7R4vtMwGArT77UjAWZ5hmd2zbJGqmFrFXsfqFuUZWI1-QNwRynuw-E1rMLB2ew-Dtw66oG71Xlk4nAyPPuLErv4otYuxqJ0YTEPLCCMvZ-RY-_DgPO0wgm3Mwn_f7iicEzGiof2R3bre2Rf5IP51nfe82IAyF2fqUnISD3u9LaK5yUn__4DoLV4s7IEAAA.ttY3JDC124leYBLHRrfWCmAViAWNf9FipMmucdfQTNitkvnAAmcFyy3rmKPEFJzfAm1OtGo97VyUDD24Mrc0tcecPXWdGkTWNWPShqcs_ipTZI188yRDPn9AmzMwAHWuL65LSOXnxg31-hzRXzKwh2aTmWt3trPa5x1pfb1wSqjDYpG1cTvKdsOV9PG7IzeHFzyXMvM9b4qHYW6Id39m-njB0UTg7zDuu44XWWO9aTmXJDlYDeOVitDIaUBN3IlSg5TtuEEY7MSkusQDN7NaeLsx9R0YXEhwxg52-swKa5jJ8dsZFIkpW8QOG0R2qhEh_BweqgtSzDrAf54pwRC8ko8TX1M4QUEsYkWVAPlvDTFb7j94zVmIDDA1Cbd_XnCrO3YU6E4DUQGTxSeQBHrkw21VxT0cNadyAFl37j7r2EkiLIXOPmhCzRwxHbSCxJth-SCheFIMiq6v8F2ErLTKVg5nays1U3OS2w1IhUNn85FhKwuJ67X2QWwVTE8YdonunbJMQGdVvDOQX32--AF67wUDmMfaZGHt3K46Fnht1U22FPCVKPsMiZPE2FaXvlDnQsWUlN0pInZAMGLpbq8CacX0ZAt0KlI9mOvsxEaQYlDVt0RqVYR9H-1OUUThbhtTfAtzT0RBLPWAI9cqLdljSMAVw5IJyjCFMauIfQzM97s
  account:
    all-accounts:
      endpoint: /api/v2/accounts
    balance:
      endpoint: /api/v2/accounts/{accountUid}/balance
    confirmation-of-funds:
      endpoint: /api/v2/accounts/{accountUid}/confirmation-of-funds?targetAmountInMinorUnits={targetAmountInMinorUnits}
  savings-goals:
    all-savings-goals:
      endpoint: /api/v2/account/{accountUid}/savings-goals
    create-savings-goal:
      endpoint: /api/v2/account/{accountUid}/savings-goals
    transfer-money-to-savings-goal:
      endpoint: /api/v2/account/{accountUid}/savings-goals/{savingsGoalUid}/add-money/{transferUid}
  transaction:
    transactions-weekly:
      endpoint: /api/v2/feed/account/{accountUid}/category/{categoryUid}?changesSince={changesSince}
    transactions-between:
      endpoint: /api/v2/feed/account/{accountUid}/settled-transactions-between?minTransactionTimestamp={minTransactionTimestamp}&maxTransactionTimestamp={maxTransactionTimestamp}