spring:
  application:
    name: starling

starling:
  baseUrl: https://api-sandbox.starlingbank.com
  accessToken: eyJhbGciOiJQUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_21Ty5KjMAz8lSnOoykMhEduc9sf2A8QlkhcAzZlm8xObe2_r8EQQio3ultqSZb4myjnknOCowLiwXw4j7ZX-tKi_vqQZkjeEze1IYKyCnPiBupc5FAU2QlaxhLkqasFVyTLQoZg_jMmZ1GJIs2zJivfE4V-IfKmKE8zgVKaSftfpie2vxWt3mVTllCdZAvBmoN3nUF6avIcm0I0SMHbmy_WMYNF2nV5KqBDDhltRoBpJuDUiJqqjKuinjPCWJ9SsnMPddKCQUiZQiGEgLoSLaQosryqizLL5iwnzcjzo8RO4bq0ChoHPltGensS_M_4JChi7VWn2B75Xjl_YFZAZEOTZybl7yAq3qO8DnyP3PG3VZ7fcPJXY5ULKwOlSd0UTdjH4BZ71HJtTaIlkEZ7a_pYaGZWzehO2QG9MhpMB92kaW1ATs6bYZuDB1Rr9oCa0POZuOfQxwaXsIE9BoRnGeAsbnjJHPGHeZMiWE0i2INADXhZPaO2f4K3qB3Kuec7Db2RYfrdOxJg5md4ZtcsazrVb6Vi7QO1RFmWrEZ_AO4oxX04vIVVOLiYvY8Dt4564BafRyYO14Vnf2Gxiy-8djGayivT1DNBGHs_I8fehwGncYUjbmcS_v9wReGYjKWH8kd2q3tkX-SD-dZ33vPcAEh3e6ZG6iL1uNNlFc9LTv79B2oZmsqyBAAA.zDu4jl6U4e2R25BXqY2LAJXvH-1TrysyY3rFlLI640UHkuhFp5VEkXlAUPrjxdfx4PITWsqGECSIzp94tds_UGUroR1t1E15z_nh4I2y-HSbdAIMMg_qlVleqMuN_ncsHoANFKYLV5zT7hEHKGlwvmfvjctOeOh55G5GlZknF8S7CQOVqYybjaKj0UCdGHbuneJsI4MOqDW6eWpyrOp_qM-AHH442_gjMQPFcdxxsJvEn8k3-lSnLqUDMXloAUtlRs6YP6ELjRF4o2JYPZAZYCyGC-3eYiJQwS5yUdMr-A6BFgjSJIUPTEIzoF_FCvwFftuwBH-wk-hOqrfqyXa7vLSBAjhKFPwa_rLFC8P2Ti9m6ioPjeo1kJd34FjJU9GmWPryNfDzbvQ5eCaCoyU3I2y1wzOvUfPZfhOgXBFzBsDoSFBFqVgNME2iwJw7i_e0o23x0G2FwOZPS-G404sbyqRh-kc-lpgpnr4sEQdZEn2FX-4K0dRbypJxU8MG_13t1_1_V0-yvEufxmhVwHI5helV5WLB04BwOPI1-z_t9DYtQxG0EWFhhrZFdfKBUtoGPZrzjLWQCeALKdHqwsvpwRbZ1ZVnYHESmC2jATiu5jowudTz998uI-7CSXV3Gkfs1Y12xCjEDd95mOp3JSa2mQqUuoAq5Jo-mUesE_gsfxw
  account:
    all-accounts:
      endpoint: /api/v2/accounts
    balance:
      endpoint: /api/v2/accounts/{accountUid}/balance
    confirmation-of-funds:
      endpoint: /api/v2/accounts/{accountUid}/confirmation-of-funds?targetAmountInMinorUnits={targetAmountInMinorUnits}
  savings-goals:
    all-savings-goals:
      endpoint: /api/v2/account/{accountUid}/savings-goals
    create-savings-goal:
      endpoint: /api/v2/account/{accountUid}/savings-goals
    transfer-money-to-savings-goal:
      endpoint: /api/v2/account/{accountUid}/savings-goals/{savingsGoalUid}/add-money/{transferUid}
  transaction:
    transactions-weekly:
      endpoint: /api/v2/feed/account/{accountUid}/category/{categoryUid}?changesSince={changesSince}
    transactions-between:
      endpoint: /api/v2/feed/account/{accountUid}/settled-transactions-between?minTransactionTimestamp={minTransactionTimestamp}&maxTransactionTimestamp={maxTransactionTimestamp}