spring:
  application:
    name: starling

starling:
  baseUrl: https://api-sandbox.starlingbank.com
  accessToken: eyJhbGciOiJQUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_21Ty5KjMAz8lSnOoynextzmtj-wHyBskbgGbMo2mZ3a2n9fgyGEVC4pultqSZbyN1HOJW2CkwJJo_lwHu2g9KVD_fUhzJi8J27uQgTlWBGVJRQFa6DsC4SOEYMqK0teUVqndRGC6c-UtBnLyjxlGePviUIfiSwwC4FCmFn7X2aQZH8ruXkXddpAzjmDkuUNoAhVJPGUy6bLRZUGb2--SG8ZomYp5xUgxwrKpqqhq3kJrKjzrOI8_CwZYaxPIci5ow4XvQDWlR2UImeARZUC9o0sWFZwkdfLwMJMtDxK7BSua6ugcaTWEsq3J8H_TE-CkqS96hXZMz8o50_MBqS0ocmWpPJ3EBXvUVxHukce-NsqT284-6uxyoWVgdJS3ZSccYjBHQ6oxdaaQCtBGO2tGWKhhdk0o3tlR_TKaDA99LOWWwNidt6M-xw0otqyR9QSPbWSBgp97HANG8ljQNiKABdxx2vmhD9EuxTBZhLBEQRqxMvmGbXjE7xF7VAsPd9pGIwI0x_ekQCzPMMzu2VZ06thLxVrn6g1ypIgNfkTcGcp7sPhLazCwcUcfZy4bdQTt_o8MnG4Pjz7C4tDfOF1iNFUXEnOA0kIYx9n5Mj7MOA8bXDC_UzC_z9cUTgmY-VD-TO71z2zL_LBfOs772lpAIS7PVOT7CP1uNN1Fc9LTv79B9mtkHuyBAAA.Y6eN0-BOs7dHy61K-XNti9I4txQA8068EaCn0ESX9WTsu2HoRl3j_g-6-9sZY88scAJbWsGgTBGSb3m_bRWdkvAitHvfQ3mqLkQyDY6aIzpclblgWJsITrnGAEc9KEQFQ6XhhJAuTkR-aQdAAuJmqFmRZwLjGHfiz7aYwEV9jD17jGG0_PlRpFxnpt3MfMkYLxzyiJ0HPbcDkfDTo_7MUkSBaBKF3vQlGRCknlJErTzgD0Fdp0yIylCE2nlHtBJAHHJS7DI4j2adU3Vt51Msam_ejCPplFfbeZ6EdTzZU9rnXVoZ6AbANo8AbQVhVc2Y7UcGiHfx4A5L5gIw0WpbyKgD2tswiOL4llHat1dgJ6Pm7UQl7yqFU6m9_iEgm--lLwFBngvlgQ4Zsjg8sogS2cl8Zr64bL3VtKITnMZZwNR1gwRg8llzGGDASAsjbmxe9tNaX2-VMq2UQ1aYream1FquSsjM6dI5L6mmr2owkhDh2gnMmt2avasCV6AjcvFW1ab715I6Rvs6x7YL1spwbB752JmGVogED7IohF-Zc6Qtc4OJYSqt_usNYKbIGDcmLkWl0zebUGT7IsY2SLrFkuyvtTZXpJl3EFsvDQKBj-xk0GKVoG6eYHX996RAdrGnYsUf8jVn9hM-iZ70UzCGz7em06YvisWWlrC7Fqq2550
  account:
    all-accounts:
      endpoint: /api/v2/accounts
    balance:
      endpoint: /api/v2/accounts/{accountUid}/balance
    confirmation-of-funds:
      endpoint: /api/v2/accounts/{accountUid}/confirmation-of-funds?targetAmountInMinorUnits={targetAmountInMinorUnits}
  savings-goals:
    all-savings-goals:
      endpoint: /api/v2/account/{accountUid}/savings-goals
    create-savings-goal:
      endpoint: /api/v2/account/{accountUid}/savings-goals
    transfer-money-to-savings-goal:
      endpoint: /api/v2/account/{accountUid}/savings-goals/{savingsGoalUid}/add-money/{transferUid}
  transaction:
    transactions-weekly:
      endpoint: /api/v2/feed/account/{accountUid}/category/{categoryUid}?changesSince={changesSince}
    transactions-between:
      endpoint: /api/v2/feed/account/{accountUid}/settled-transactions-between?minTransactionTimestamp={minTransactionTimestamp}&maxTransactionTimestamp={maxTransactionTimestamp}
